### PR TITLE
Pushing all updates

### PR DESCRIPTION
**Pull request by msashawky**

### CODE REVIEW

**Comment by ahmedeagle** [comment]
sorry but the queue and cache code  take from my pull request  thanks ,

**Comment by ahmedeagle** [comment]
resetWeeklyVisits cron jobs here will only have the last 7 days view and every week you rest counter  but there are now  way to know the count of all user views or visits only you done the last 7 days and the previous   lost

**Comment by msashawky** [comment]
> sorry but the queue and cache code take from my pull request thanks ,

@ahmedeagle I wandered!!!! what is the part that was taken from your code? I didn't add a queue or get your published edits by the way. I was asked to do this task by @sameh0 according to a vacancy process, so please if you have any concerns with my published edits please contact the recruiter from Reach Network and He can compare all source codes.

Although I'm not be claimed to explain anything , here is the [Cache](https://laravel.com/docs/7.x/cache#retrieving-items-from-the-cache) from laravel Documentation you can check it!

**Comment by msashawky** [comment]
> resetWeeklyVisits



> he count of all user views or visits only you done the last 7 days and the previous l

Excuse me, I don't know if you are a part of the Interviewing process to review my code or one of the vacancy applicants, please explain since I'm not claimed to discuss like this. so please again contact the recruiter for any problems or reviews

**Comment by ahmedeagle** [comment]
Sorry the first message sent by wrong


في السبت، ٢٢ أغسطس، ٢٠٢٠ ٠٠:١٨ Mohamed Shawky <notifications@github.com>
كتب:

**Pull request closed without merging**
